In [121]:
import numpy as np
from plotly import express as px
import math

Number of steps for the algorithms 1 and 2:

$Alg_1 = 8 \cdot n^2$

$Alg_2 = 64 \cdot n \cdot lg(n)$

In [3]:
X = np.array([5, 10, 20, 30, 45, 46, 47, 50, 55, 60, 65, 70])

steps1 = 8 * X ** 2
steps2 = 64 * X * np.log2(X)

In [4]:
px.line(X, x=X, y=[steps1, steps2])

In [5]:
steps1

array([  200,   800,  3200,  7200, 16200, 16928, 17672, 20000, 24200,
       28800, 33800, 39200])

In [6]:
steps2

array([  743.01699036,  2126.03398073,  5532.06796146,  9421.22994357,
       15816.53691743, 16261.36639863, 16708.20326585, 18060.33980728,
       20350.38619161, 22682.45988714, 25053.0501022 , 27459.18791591])

Alg1 is more eficient than Alg2 for a $\mathbf{X}$ with length 45

---

Number of steps for the algorithms 3 and 4:

$Alg_3 = 600 \cdot n^2$

$Alg_4 = 2^n$

In [7]:
X = np.array([5, 10, 11, 12, 13, 15, 17, 18, 20, 21])

steps3 = 600 * X ** 2
steps4 = 2 ** X

In [8]:
px.line(X, x=X, y=[steps3, steps4])


In [9]:
print(steps3)
print(steps4)

[ 15000  60000  72600  86400 101400 135000 173400 194400 240000 264600]
[     32    1024    2048    4096    8192   32768  131072  262144 1048576
 2097152]


The algorithm Alg3 becomes faster than Alg4 if $n \ge 18$, in other words, form a $\mathbf{X}$ with length greater than 18. 

---

Problema 1-1

In [462]:
t1 = 1000
t2 = 1000 * 60
t3 = 1000 * 60 * 60
t4 = 1000 * 60 * 60 * 24
t5 = 1000 * 60 * 60 * 24 * 30
t6 = 1000 * 60 * 60 * 24 * 30 * 12
t7 = 1000 * 60 * 60 * 24 * 30 * 12 * 100

In [212]:
time_lg = np.log2(10**19) / t1
time_sqrt = np.sqrt(10**6) / t1
time = 1000 / t1
time_n_lg_n = 140 * np.log2(140) / t1
time_sq2 = 31 ** 2 / t1
time_sq3 = 10 ** 3 / t1
time_2_sq_n = 2 ** 10 / t1
time_fat = math.factorial(6) / t1



print(f"Time: lg(n): {time_lg} for n = 10^19")
print(f"Time: sqrt(n): {time_sqrt} n = 10^6")
print(f"Time: n: {time} for n = 1000")
print(f"Time: n * log2(n): {time_n_lg_n} for n = 140")
print(f"Time: n ** 2: {time_sq2} for n = 31")
print(f"Time: n ** 3: {time_sq3} for n = 10")
print(f"Time: 2 ** n: {time_2_sq_n} for n = 10")
print(f"Time: n!: {time_fat} for n = 6")

Time: lg(n): 0.06311663380285988 for n = 10^19
Time: sqrt(n): 1.0 n = 10^6
Time: n: 1.0 for n = 1000
Time: n * log2(n): 0.9980996223722952 for n = 140
Time: n ** 2: 0.961 for n = 31
Time: n ** 3: 1.0 for n = 10
Time: 2 ** n: 1.024 for n = 10
Time: n!: 0.72 for n = 6


In [213]:
time_lg = np.log2(10**19) / t2
time_sqrt = np.sqrt(11 ** 9 + 10 ** 9 + 10 ** 8) / t2
time = 60000 / t2
time_n_lg_n = 4890 * np.log2(4890) / t2
time_sq2 = 244 ** 2 / t2
time_sq3 = 39 ** 3 / t2
time_2_sq_n = 2 ** 15 / t2
time_fat = math.factorial(8) / t2



print(f"Time: lg(n): {time_lg} for n = 10^19")
print(f"Time: sqrt(n): {time_sqrt} n = {11 ** 9 + 10 ** 9 + 10 ** 8}")
print(f"Time: n: {time} for n = {60000}")
print(f"Time: n * log2(n): {time_n_lg_n} for n = {4890}")
print(f"Time: n ** 2: {time_sq2} for n = {244}")
print(f"Time: n ** 3: {time_sq3} for n = {39}")
print(f"Time: 2 ** n: {time_2_sq_n} for n = {15}")
print(f"Time: n!: {time_fat} for n = {8}")

Time: lg(n): 0.0010519438967143315 for n = 10^19
Time: sqrt(n): 0.980071949031181 n = 3457947691
Time: n: 1.0 for n = 60000
Time: n * log2(n): 0.998832928111927 for n = 4890
Time: n ** 2: 0.9922666666666666 for n = 244
Time: n ** 3: 0.98865 for n = 39
Time: 2 ** n: 0.5461333333333334 for n = 15
Time: n!: 0.672 for n = 8


In [281]:
time_lg = np.log2(10**19) / t3
time_sqrt = np.sqrt((val2 := 10 ** 13 + 2 * 10 ** 12 + 12 ** 11)) / t3
time = (val3 := 12 ** 6 + 6 * 10 ** 5) / t3
time_n_lg_n = (val4 := 2 * 10 ** 5 + 3 * 10 ** 3) * np.log2(val4) / t3
time_sq2 = (val5 := 1896) ** 2 / t3
time_sq3 = (val6 := 153) ** 3 / t3
time_2_sq_n = 2 ** (val7 := 21) / t3
time_fat = math.factorial((val8 := 9)) / t3



print(f"Time: lg(n): {time_lg} for n = 10^19")
print(f"Time: sqrt(n): {time_sqrt} n = {val2}")
print(f"Time: n: {time} for n = {val3}")
print(f"Time: n * log2(n): {time_n_lg_n} for n = {val4}")
print(f"Time: n ** 2: {time_sq2} for n = {val5}")
print(f"Time: n ** 3: {time_sq3} for n = {val6}")
print(f"Time: 2 ** n: {time_2_sq_n} for n = {val7}")
print(f"Time: n!: {time_fat} for n = {val8}")

Time: lg(n): 1.7532398278572192e-05 for n = 10^19
Time: sqrt(n): 0.991593071136505 n = 12743008370688
Time: n: 0.9961066666666667 for n = 3585984
Time: n * log2(n): 0.9941992780486096 for n = 203000
Time: n ** 2: 0.99856 for n = 1896
Time: n ** 3: 0.9948825 for n = 153
Time: 2 ** n: 0.5825422222222222 for n = 21
Time: n!: 0.1008 for n = 9


In [350]:
time_lg = np.log2(10**19) / t4
time_sqrt = np.sqrt((val2 := 7 * 10 ** 15)) / t4
time = (val3 := 8 * 10 ** 7) / t4
time_n_lg_n = (val4 := 3 * 10 ** 6 + 9 * 10 ** 5) * np.log2(val4) / t4
time_sq2 = (val5 := 9280) ** 2 / t4
time_sq3 = (val6 := 442) ** 3 / t4
time_2_sq_n = 2 ** (val7 := 26) / t4
time_fat = math.factorial((val8 := 11)) / t4



print(f"Time: lg(n): {time_lg} for n = 10^19")
print(f"Time: sqrt(n): {time_sqrt} n = {val2}")
print(f"Time: n: {time} for n = {val3}")
print(f"Time: n * log2(n): {time_n_lg_n} for n = {val4}")
print(f"Time: n ** 2: {time_sq2} for n = {val5}")
print(f"Time: n ** 3: {time_sq3} for n = {val6}")
print(f"Time: 2 ** n: {time_2_sq_n} for n = {val7}")
print(f"Time: n!: {time_fat} for n = {val8}")

Time: lg(n): 7.30516594940508e-07 for n = 10^19
Time: sqrt(n): 0.9683565121922171 n = 7000000000000000
Time: n: 0.9259259259259259 for n = 80000000
Time: n * log2(n): 0.9883178993503049 for n = 3900000
Time: n ** 2: 0.9967407407407407 for n = 9280
Time: n ** 3: 0.9994315740740741 for n = 442
Time: 2 ** n: 0.776722962962963 for n = 26
Time: n!: 0.462 for n = 11


In [401]:
time_lg = np.log2(10**19) / t5
time_sqrt = np.sqrt((val2 := 6 * 10 ** 18)) / t5
time = (val3 := 2 * 10 ** 9 + 5 * 10 ** 8) / t5
time_n_lg_n = (val4 := 9 * 10 ** 7 + 7 * 10 ** 6) * np.log2(val4) / t5
time_sq2 = (val5 := 50650) ** 2 / t5
time_sq3 = (val6 := 1360) ** 3 / t5
time_2_sq_n = 2 ** (val7 := 31) / t5
time_fat = math.factorial((val8 := 12)) / t5



print(f"Time: lg(n): {time_lg} for n = 10^19")
print(f"Time: sqrt(n): {time_sqrt} n = {val2}")
print(f"Time: n: {time} for n = {val3}")
print(f"Time: n * log2(n): {time_n_lg_n} for n = {val4}")
print(f"Time: n ** 2: {time_sq2} for n = {val5}")
print(f"Time: n ** 3: {time_sq3} for n = {val6}")
print(f"Time: 2 ** n: {time_2_sq_n} for n = {val7}")
print(f"Time: n!: {time_fat} for n = {val8}")

Time: lg(n): 2.4350553164683597e-08 for n = 10^19
Time: sqrt(n): 0.9450191908885719 n = 6000000000000000000
Time: n: 0.9645061728395061 for n = 2500000000
Time: n * log2(n): 0.9928833707239956 for n = 97000000
Time: n ** 2: 0.9897463348765432 for n = 50650
Time: n ** 3: 0.9704691358024692 for n = 1360
Time: 2 ** n: 0.8285044938271605 for n = 31
Time: n!: 0.1848 for n = 12


In [460]:
time_lg = np.log2(10**19) / t6
time_sqrt = np.sqrt((val2 := 10 ** 19 + 8 * 10 ** 18)) / t6
time = (val3 := 3 * 10 ** 10) / t6
time_n_lg_n = (val4 := 9 * 10 ** 8 + 9 * 10 ** 7 + 9 * 10 ** 6) * np.log2(val4) / t6
time_sq2 = (val5 := 10 ** 5 + 7 * 10 ** 4 + 5 * 10 ** 3) ** 2 / t6
time_sq3 = (val6 := 3140) ** 3 / t6
time_2_sq_n = 2 ** (val7 := 34) / t6
time_fat = math.factorial((val8 := 13)) / t6



print(f"Time: lg(n): {time_lg} for n = inf")
print(f"Time: sqrt(n): {time_sqrt} n = {val2}")
print(f"Time: n: {time} for n = {val3}")
print(f"Time: n * log2(n): {time_n_lg_n} for n = {val4}")
print(f"Time: n ** 2: {time_sq2} for n = {val5}")
print(f"Time: n ** 3: {time_sq3} for n = {val6}")
print(f"Time: 2 ** n: {time_2_sq_n} for n = {val7}")
print(f"Time: n!: {time_fat} for n = {val8}")

Time: lg(n): 2.029212763723633e-09 for n = inf
Time: sqrt(n): 0.13640177106221982 n = 18000000000000000000
Time: n: 0.9645061728395061 for n = 30000000000
Time: n * log2(n): 0.9601984801851684 for n = 999000000
Time: n ** 2: 0.9846000514403292 for n = 175000
Time: n ** 3: 0.9953428497942387 for n = 3140
Time: 2 ** n: 0.552336329218107 for n = 34
Time: n!: 0.2002 for n = 13


In [499]:
time_lg = np.log2(10**19) / t7
time_sqrt = np.sqrt((val2 := 10 ** 19 + 8 * 10 ** 18)) / t7
time = (val3 := 3 * 10 ** 12) / t7
time_n_lg_n = (val4 := 8 * 10 ** 10) * np.log2(val4) / t7
time_sq2 = (val5 := 10 ** 6 + 7 * 10 ** 5) ** 2 / t7
time_sq3 = (val6 := 14500) ** 3 / t7
time_2_sq_n = 2 ** (val7 := 41) / t7
time_fat = math.factorial((val8 := 15)) / t7



print(f"Time: lg(n): {time_lg} for n = inf")
print(f"Time: sqrt(n): {time_sqrt} n = inf")
print(f"Time: n: {time} for n = {val3}")
print(f"Time: n * log2(n): {time_n_lg_n} for n = {val4}")
print(f"Time: n ** 2: {time_sq2} for n = {val5}")
print(f"Time: n ** 3: {time_sq3} for n = {val6}")
print(f"Time: 2 ** n: {time_2_sq_n} for n = {val7}")
print(f"Time: n!: {time_fat} for n = {val8}")

Time: lg(n): 2.0292127637236332e-11 for n = inf
Time: sqrt(n): 0.0013640177106221982 n = inf
Time: n: 0.9645061728395061 for n = 3000000000000
Time: n * log2(n): 0.931565868026585 for n = 80000000000
Time: n ** 2: 0.9291409465020576 for n = 1700000
Time: n ** 3: 0.9801392103909465 for n = 14500
Time: 2 ** n: 0.706990501399177 for n = 41
Time: n!: 0.42042 for n = 15
